### ISSUE TITLE
Enhancement: Mention issue tracker in FAQ and/or contact site

### ISSUE THREAD

**Issue by vog** [ioccc-src/winner#14]
Currently, question 4 of [the FAQ](https://www.ioccc.org/faq.html) states:

> Q: I found a bug in a previous winner, what should I do?
> A: We do not \``maintain'' the contest winners. The code is made available on an ``AS IS'' basis. If you have a FIX for a entry, we suggest that you try and EMail it to the authors and to CC: us using the instructions on the contacting the IOCCC Judges page.
IF you have a FIX, and IF the author does not object, and IF your fix looks reasonable, we will add a web link to a copy of your EMail message for others to see.

Would it make sense to direct corrections to the issue tracker and/or the Pull Requests section? Chances are that *if* the original author is still active, they are likely on GitHub and perhaps already watching the IOCCC winner repository. Even if not, kindly asking the contributor to file a pull request in addition to emailing the author and judges could save some time for the author as well as the judges.

Moreover, would it make sense to mention the issue tracker in [the contact page](https://www.ioccc.org/contact.html) as well, e.g. for public questions and/or correction proposals to the IOCCC site itself?

**Comment by lcn2** [comment]
Good point @vog.  We plan to address how winning authors may request that we change, correct, remove, improve their author information.  We also plan to make it easier for winning authors and others to request that we improve IOCCC entries.  These are some of the FUNDAMENTAL reasons why we are undergoing this multi-month long project to retool how the IOCCC is run.

We will keep this issue open as a reminder that we need to explain how, in the FAQ, author's and others can request modification of content.

More details will be announced as we work out some of the fine details.

**Comment by SirWumpus** [comment]
Maybe create an IOCCC Fan / Dreamer / Drooler page where contributors can point to corrected / updated / spoiler versions of their favourites.

**Comment by lcn2** [comment]
We created a [Discussion page](u[r](https://github.com/ioccc-src/winner/discussions)l) @SirWumpus .. perhaps that will work.

We need to organize it .. but for now it can be a placeholder.

**Comment by lcn2** [comment]
FYI: This issue is being addressed as part of the web site rebuild.

**Comment by lcn2** [comment]
As we plan to use the GitHub issues and GitHub pull requests in the new web site.  Those things are actively being worked on in the [temp-test-ioccc repo](https://github.com/ioccc-src/temp-test-ioccc), that when it is ready, turn into a big pull request agains this repo.

We will close this issue as the [temp-test-ioccc repo](https://github.com/ioccc-src/temp-test-ioccc), once merged into this repo, addresses this enhancement.
