### ISSUE TITLE
Future rules / guidelines format

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/winner#17]
The Rules and Guidelines files should use Markdown formatting.  Not sure how diff marks are handled in Markdown (new extension?), but makes for better GitHub viewing.

**Comment by lcn2** [comment]
That is an excellent suggestion, @SirWumpus!

We will keep this issue open for now as a reminder.

=-=

**BTW/FYI**: We continue to plan to capture, for historic purposes, the tool and doc set used for a given contest.

> You can see that attempt, for those years we remembered to do so (or were able to find) they are found in the top level of a given IOCCC winners directory.

Going forward, we plan to continue to save the rules, guidelines, and tools for a given IOCCC.  In the case of tools, this will be a release of the [mkiocccentry](https://github.com/ioccc-src/mkiocccentry).

=-=

**BTW/FYI**: We plan to hold a mock IOCCC (probably called **IOCCCM00**): a dry run of the IOCCC where we test the tool chain PLUS the full "**register for  the contest thru winner announcement**" cycke.  Only as judges we won't spend human time judging entries.   Any code that is submitted **IOCCCM00** won't be released.  We won't even look at it.  We will probably just run `file(1)` on the `prog.c` to see what it prints, look at `ls(1)` and `wc(1)` and `iocccsize` output too.

There won't be _winning entries._  Instead we announce a thank to those who took the time to register and submit entries.  Special thanks (awards) will be given to those who contributed to the improvement of the process as a way to test the _tweet winners_ and the _rapid release of the winners_. 

There will be some form of a directory created with awards, where the source code will be a some _hello, world!_ style program we supply that also prints a thank you.

If a _show stopper_ is found during the  **IOCCCM00**, we can abort the contest, fix stuff, and re-open the contest.  While we will make an effort to be ready a full **IOCCCM00**, however should something go wrong, won't risk losing someone's hard work of a real IOCCC entry.

**Comment by SirWumpus** [comment]
All that with a Queen Elisabeth accent and all will be right. Pip pip.

**Comment by SirWumpus** [comment]
For an `IOCCCM00` it might be simplest to resubmit old winners (and losers) to test the tools since we already know that they should pass in some fashion.

**Comment by lcn2** [comment]
We need some people to package entries and submit them to the submission server portal.  If they wish to package old winners, they are welcome to do so.

**Comment by lcn2** [comment]
Future IOCCC will use markdown for both rules and guidelines.  The 1st implementation will occur during _IOCCCMOCK_, a test IOCCC run to beta test the new IOCCC toolset and web site.   The [temp-test-ioccc repo](https://github.com/ioccc-src/temp-test-ioccc) is being developed to support this idea as well.

**Comment by xexyl** [comment]
> Future IOCCC will use markdown for both rules and guidelines. The 1st implementation will occur during _IOCCCMOCK_, a test IOCCC run to beta test the new IOCCC toolset and web site. The [temp-test-ioccc repo](https://github.com/ioccc-src/temp-test-ioccc) is being developed to support this idea as well.

Indeed it is! I'm working hard on it. Well the text to markdown in general part and many other fixes / improvements .. obviously not the rules / guidelines. Personally I prefer the text for rules and guidelines but I guess seeing html might be nice for some people.

But for now I must try and rest. I know I won't succeed but I'm going to try I think. I'll continue README.md format fixes in a bit I'm sure. I believe I've replied to everything important and perhaps things not that important (like this comment maybe? ... except to say I hope to work on the README.md files in a bit).
