### ISSUE TITLE
[Rule Guideline] Rule 13 impugns valid source with UTF-8 characters

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/winner#34]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like it

### Which Rule and/or Guideline has a problem?

Rule 13:

Any C source that fails to compile because of unescaped octets with the high bit set (octet value >= 128) might be rejected.

### What is wrong with the Rule and/or Guideline?

The default compiler is `-std=gnu17`, which allows for UTF-8 in source code.

Even though the rule technically would allow UTF-8 in source code because the could would compile, the threat of being rejected tends to discourage use of UTF-8 character in C code.

### How do you recommend we fix the problem?

Replace Rule 13 with something fun/humorous about the number 13.

Perhaps the current Rule 13 should be replace with:

```
7 out of 13 UTF-8 characters in C code agree that this rule number is lucky enough to be a prime number.
```

### Anything else?

See Discussion #28 for more information.

**Comment by lcn2** [comment]
We have made test modifications to entry source code.  There was no ill effects when the various bin tools processed such entries.

**Comment by lcn2** [comment]
This guideline related to the old Rule 13 would need to be removed or replaced:

[Rule 13](rules.html#rule13)  states any C source that fails to compile because of unescaped octets with the high bit set (octet value >= 128) **might** be rejected.
Instead of unescaped octets, you should use \octal or \hex escapes:

``` <!---c-->

              /* 123456789 123456789 123456789 123456 */
    char *foo = "This string is 36 octets in length \263";
          /* This octet requires 4 octets of source ^^^^ */
    if (strlen(foo) == 36) printf("foo is 36 octets plus a final NUL\n");
    else printf("This code should not print this message\n");
```

**Comment by lcn2** [comment]
Here is our proposed change to solve this issue:

```diff
diff --git a/news.md b/news.md
index eb790c5fb..86ed6c066 100644
--- a/news.md
+++ b/news.md
@@ -14,6 +14,14 @@ for more information on Mastodon.
 </div>


+## 2024-12-30
+
+The IOCCC [Rule 13](next/rules.html#rule13) no longer discourages the
+use of UTF-8 in C source.  Since the days of `-std=gnu17` compilers,
+UTF-8 characters do not impose a compiler problem.  The related guideline
+states that "Rule 13 no longer discourages the use of UTF-8 +characters in C code".
+
+
 ## 2024-12-28

 ### Good News Everyone! :-)
diff --git a/next/guidelines.md b/next/guidelines.md
index fddbca690..0a0abdda2 100644
--- a/next/guidelines.md
+++ b/next/guidelines.md
@@ -1560,18 +1560,10 @@ prevent such trailing control-M's being added.
 One should restrict libcurses to portable features found on BSD
 or Linux curses.

-[Rule 13](rules.html#rule13)  states any C source that fails to compile because of unescaped
-octets with the high bit set (octet value >= 128) **might** be rejected.
-Instead of unescaped octets, you should use \octal or \hex escapes:
-
-``` <!---c-->
-
-              /* 123456789 123456789 123456789 123456 */
-    char *foo = "This string is 36 octets in length \263";
-          /* This octet requires 4 octets of source ^^^^ */
-    if (strlen(foo) == 36) printf("foo is 36 octets plus a final NUL\n");
-    else printf("This code should not print this message\n");
-```
+<p class="leftbar">
+[Rule 13](rules.html#rule13) no longer discourages the use of UTF-8
+characters in C code.
+</p>

 <p class="leftbar">
 It is a very good idea to, in your `remarks.md` file, tell us why you
diff --git a/next/rules.md b/next/rules.md
index 34dbfcff1..05d96105a 100644
--- a/next/rules.md
+++ b/next/rules.md
@@ -55,7 +55,7 @@ Jump to: [top](#)


 <p class="leftbar">
-These [IOCCC rules](rules.html) are version **28.15 2024-12-28**.
+These [IOCCC rules](rules.html) are version **28.16 2024-12-29**.
 </p>

 <p class="leftbar">
@@ -604,8 +604,7 @@ Jump to: [top](#)
 </div>

 <p class="leftbar">
-Any C source that fails to compile because of unescaped octets with
-the high bit set (octet value >= 128) **_might_** be rejected.
+7 out of 13 UTF-8 characters in C code agree that this rule number is lucky enough to be a prime number.
 </p>

```

Comments welcome.

**Comment by xexyl** [comment]
@sirwumpus since you brought up this issue: what are your thoughts?

As for my thoughts I hope to get to this today but might not be until tomorrow. 

Still it might go well to decide this before I make the fixes in the two files.

**Comment by SirWumpus** [comment]
I like it.

**Comment by lcn2** [comment]
With commit 9dd70f0fc9757045d1825b20cc383fdc3e45a8d8 we have resolved this issue.

Thank you @SirWumpus for your input!
